---
- hosts: webservers
  tasks:
   - name: Going to create demo.txt file
     file:
        path: /tmp/demo.txt
        state: touch
        mode: 0777
   - name: Copy demo.txt file into mnt directory
     copy:
        src: /tmp/demo.txt
        dest: /mnt/exmple.txt
